site_name: CTI Intelligence
site_description: "Report aggiornati su Threat Actors e TTPs"
site_author: "Lorenzo"

docs_dir: 'docs'

theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: cyan
  features:
    - navigation.instant
    - navigation.tracking
    - search.suggest
    - search.highlight

plugins:
  - search
  - roamlinks

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true

nav:
  - Home: index.md
  - Tutti i Report: 
      - TTP & Malware: TTP_&_Malware/
      - Actors: Actors/
      - Reports: Reports/
      - Data: data/