site_name: CTI
site_description:
site_author: Lorenzo

docs_dir: '.'
site_dir: 'site'
theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: cyan
  features:
    - navigation.instant
    - navigation.tracking
    - search.suggest
    - search.highlight

plugins:
  - search
  - roamlinks

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true

nav:
  - Home: README.md
  - Threat Actors: Actors/
  - Malware & TTP: TTP_&_Malware/